# Site settings
title: Tutorial Jekyll # Título do Blog
subtitle: Como construir um blog com Jekyll # Subtítulo do Blog, opcional
description: "Tutorial de como construir um blog com Jekyll, feito por Mateus Medeiros" # Descrição do Blog
url: "http://devmateusmedeiros.com.br/tutorial-jekyll" # Endereço do nosso blog

# Author Settings
author:
    name: Mateus Medeiros # Nome do autor
    img: /assets/img/perfil.jpg # Imagem do Autor
    blog: http://devmateusmedeiros.com.br # Blog do autor
    email: mateus.sousamedeiros@gmail.com # Email do autor
    twitter: mateussousam # Twitter do autor
    github:  mateussmedeiros # GitHub do autor
    bio: Desenvolvedor Front End apaixonado por novas tecnologias. Sou apaixonado pelo que faço e procuro aprender cada dia mais. # Descrição do autor

# Build settings
markdown: kramdown # Estilo do Markdown
permalink: /:categories/:title/ # Configuração dos links do blog
css_folder:  "/assets/css" # Caminho dos arquivos css
js_folder:  "/assets/js" # Caminho dos arquivos js
img_folder:  "/assets/img" # Caminho das imagens
sass:
    style: compressed # Configuração dos arquivos css gerados pelo sass, compressed gera o css minificado